config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    collection do
      get 'search'
    end
    collection do
      get 'favorites'
    end
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :text, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  
  geocoded_by :place
  after_validation :geocode, if: :place_changed?

  belongs_to :user
  has_one_attached :video
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :caption
  end
  validate :video_or_youtube_url
  

  def self.search(search)
    if search != ""
      Post.where( 'caption LIKE ? OR place LIKE ?', "%#{search}%", "%#{search}%" )
    else
      Post.all
    end
  end

  def favorite_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def video_or_youtube_url
    return if video.present? ^ youtube_url.present?
    errors.add(:base, 'ビデオまたはYoutube動画URLのどちらか一方を選択してください')
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :following, class_name: "User"
  
  validates :follower_id, presence: true
  validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_one_attached :image
  has_many :posts
  has_many :comments
  has_many :favorites, dependent: :destroy
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship",  dependent: :destroy
  has_many :following, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  
  with_options presence: true do
    validates :name
    validates :user_name, format: { with: /\A[a-zA-Z0-9]+\z/, message: "は半角英数字で入力してください"}
  end
  validates :email, uniqueness: true
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/, message: "は英字と数字の両方を含めて入力してください" }, on: :create

  
  def following?(user)
    following_relationships.find_by(following_id: user.id)
  end

  def follow(user)
    following_relationships.create(following_id: user.id)
  end

  def unfollow(user)
    following_relationships.find_by(following_id: user.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :user_name, :profile, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    render :index
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.user.id != current_user.id
      redirect_to post_path(comment.post)
    end
    @comment.destroy
    render :index
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_favorite

  def create
    favorite = current_user.favorites.build(post_id: @post.id)
    favorite.save
  end

  def destroy
    favorite = Favorite.find_by(post_id: @post.id, user_id: current_user.id)
    favorite.destroy
  end

  private

  def set_favorite
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :search]
  before_action :set_post, only: [:show, :edit, :update]

  def index
    @posts = Post.all.order("created_at DESC")
    @random = Post.all.order("RAND()").limit(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end

  def edit
    if @post.user_id != current_user.id
      redirect_to root_path
    end 
  end

  def update
    url = params[:post][:youtube_url]
    url = url.last(11)
    @post.youtube_url = url
    if @post.update(post_params)
      redirect_to post_path method: :get
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.user_id != current_user.id
      redirect_to root_path
    end
    post.destroy
    redirect_to root_path
  end

  def search
    @posts = Post.search(params[:keyword])
    @random = @posts.order("RAND()").limit(1)
  end

  def favorites
    @posts = current_user.favorite_posts.includes(:user).order("created_at DESC")
  end


  private

  def post_params
    params.require(:post).permit(:video, :caption, :describe, :place, :share_url).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find(params[:following_id])
    current_user.follow(@user)
  end

  def destroy
    @user = User.find(params[:id])
    current_user.unfollow(@user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show, :following, :followers]
  before_action :set_user, only: [:show, :edit, :update, :following, :followers]
  
  def show
    @posts = @user.posts.order("created_at DESC")
  end

  def edit
    if @user.id != current_user.id
      redirect_to root_path
    end 
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def following
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @users = @user.followers
    render 'show_follower'
  end

  private

  def user_params
    params.require(:user).permit(:name, :user_name, :profile, :image)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment], url: post_comments_path(@post) ) do |f| %>
    <%= f.text_area :text, placeholder:"コメントを入力...", class: "comment-text" %>
    <div class="comment-btn">
      <%= f.submit "コメント", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/comments/_index.html.erb
<% comments.reverse_each do |comment| %>
  <% unless comment.id.nil? %>
    <div class='comment-display'>
      <div class='comment-top'>
        <%= link_to user_path(comment.user.id), class: "comment-user-link" do %>
          <%if comment.user.image.present? %>
            <%= image_tag comment.user.image, class: "comment-user-icon" %>
          <% else %>
            <%= image_tag "profile_icon.png", class: "comment-user-icon" %>
          <% end %>
          <span class="comment-user-name"><%= comment.user.user_name %></span>
        <% end %>
        <span class="comment-time"><time datetime="<%= comment.created_at %>"><%= time_ago_in_words(comment.created_at)+"前" %></time></span>
        <% if comment.user == current_user %>
          <%# 削除ボタン%>
          <div class="btn-group dropleft float-right">
            <button type="button" class="btn btn-link dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            </button>
            <div class="dropdown-menu ">
              <button type="button" class="dropdown-item" data-toggle="modal" data-target="#exampleModal">
                削除する
              </button>
            </div>
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">コメントの削除</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    コメントを完全に削除しますか？
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
                    <%= link_to '削除', post_comment_path(comment.post_id, comment.id), class: "btn btn-primary", method: :delete, remote: true %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <%# /削除ボタン %>
        <% end %>
        
        <div class="comment"><%=safe_join(comment.text.split("\n"),tag(:br)) %></div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/comments/index.js.erb
$('#comments_area').html("<%= j(render 'index', { comments: @comment.post.comments }) %>")
$("textarea").val('')
$("#oppDateModal").modal("hide");
$("#oppDateModal").hide();
$(".modal-backdrop").hide();
$("body").removeClass("modal-open");

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% if post.favorite_by?(current_user) %>
    <%= button_to "お気に入り済み",  post_favorites_path(post.id), method: :delete, remote: true, class: "favorite-btn2" %>
  <% else %>
    <%= button_to "お気に入り登録",  post_favorites_path(post.id), method: :post, remote: true, class: "favorite-btn btn btn-outline-warning" %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post}) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roots</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<%= render "shared/header" %>

<div class="posts-post-contents">
  <div class="posts-post-main">
    <%= form_with model: @post, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="img-upload">
        <div class="weight-bold-text">
          動画ファイルを選択
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :video %>
        </div>
      </div>
      <div class="new-posts">
        <%= f.label :youtube_url, "Youtube URL", class: "post-edit-text", id:"post-youtube_url" %>
        <%= f.text_area :youtube_url, class:"youtube-form" %>
        
        <%= f.label :caption, "タイトル", class: "post-edit-text" %>
        <%= f.text_area :caption, class:"posts-text", id:"post-caption", maxlength:"40" %>
        
        <%= f.label :describe, "説明", class: "post-edit-text" %>
        <%= f.text_area :describe, class:"posts-text", id:"post-describe" ,rows:"7" ,maxlength:"1000" %>
        
        <%= f.label :place, "場所", class: "post-edit-text" %>
        <%= f.text_area :place, class:"posts-text", id:"post-place" %>
        
        <%= f.label :share_url, "URL", class: "post-edit-text" %>
        <%= f.text_area :share_url, class:"posts-url", id:"post-share_url", placeholder:"オススメのお店や観光スポットをURLやテキストを付けて共有しよう!" %>
      </div>
      <div class="post-btn-contents">
        <%= f.submit "編集を完了" ,class:"post-btn" %>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/second-footer" %>

app/views/posts/favorites.html.erb
<%= render "shared/header" %>

<div class="favorite-contents">
  <div class="favorite-content">
    <div class="favorite-count">お気に入り <%= @posts.count %>件</div>
    <div class="favorite-posts">
      <% @posts.each do |post| %>
        <div class="favorite-video">
          <div class="favorite-user-name">
            <%= link_to post.user.user_name, user_path(post.user.id), class: "favorite-name-link" %>
          </div>
          <%# 投稿が動画かyoutubeの共有かを判断 %>
          <% if post.video.present? %>
            <%= link_to (video_tag rails_blob_path(post.video), class: "favorite-post-video"), post_path(post.id) %>
          <% elsif post.youtube_url.present? %>
            <%= link_to  post_path(post.id) do %>
              <img class="favorite-post-video2" src="http://img.youtube.com/vi/<%=post.youtube_url%>/maxresdefault.jpg" >
            <% end %>
          <% else %>
            <div class="favorite-blank">
              <h2 class="favorite-text">お気に入りはありません。</h2>
            </div>
          <% end %>
          <%# /投稿が動画かyoutubeの共有かを判断 %>
          <div class="favorite-post-info">
            <%= link_to post.caption, post_path(post.id), class: "favorite-caption-link" %>
            <div class="favorite-post-time">
              <%= time_ago_in_words(post.created_at)+"前" %>
              <% if post.youtube_url.present? %>
                <span class="favorite-youtube-text">Youtube動画の共有</span>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
      
      
      <%# 検索結果がないときの表示 %>

      <%# /検索結果がない時の表示 %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
  <%= render "shared/header" %>

  <div class="main">
    <% if @posts.present? %>
      <div class="post-contents">

        <%# 投稿の中からランダムで５件表示する機能 %>
        <% if @posts.count >= 5 %>
          <div class="post-random">
            <div class="random-contents">
              <% @random.each do |random| %>
                <div class="random-videos">
                  <% if random.video.present? %>
                    <%= link_to (video_tag rails_blob_path(random.video), class: "random-video1"),post_path(random.id) %>
                  <% elsif random.youtube_url.present? %>
                    <%= link_to  post_path(random.id) do %>
                      <img class= "random-video2" src="http://img.youtube.com/vi/<%= random.youtube_url %>/maxresdefault.jpg" >
                    <% end %>
                  <% end %>
                  <div class="random-caption">
                    <%= link_to random.caption, post_path(random.id), class: "random-link" %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        <%# /投稿の中からランダムで5件表示する機能 %>

        <% @posts.each do |post| %>
          <div class="post-content">
            <div class="post-video-content">
              <div class="post-user-name">
                <%= link_to post.user.user_name, user_path(post.user.id), class: "post-name-link" %>
              </div>
              <%# 投稿が動画かyoutubeの共有かを判断 %>
              <% if post.video.present? %>
                <%= link_to (video_tag rails_blob_path(post.video), class: "post-video"), post_path(post.id) %>
              <% elsif post.youtube_url.present? %>
                <%= link_to  post_path(post.id) do %>
                  <img class="youtube-image" src="http://img.youtube.com/vi/<%=post.youtube_url%>/maxresdefault.jpg" >
                <% end %>
              <% end %>
              <%# /投稿が動画かyoutubeの共有かを判断 %>
            </div>
            <div class="post-info">
              <%= link_to post.caption, post_path(post.id), class: "caption-link" %>
              <div class="post-index-time"><%= time_ago_in_words(post.created_at)+"前" %>
                <% if post.youtube_url.present? %>
                  <span class="post-youtube-text">Youtube動画の共有</span>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <%# 投稿がないときの表示 %>
    <% else %>
      <div class="blank-index">
        <video class="index-video" src="/videos/video (1).mp4" loop autoplay muted type="video/mp4"></video>
        <h2 class="blank-index-text">あなたのあの場所、あの景色を共有しよう</h2>
      </div>
    <% end %>
    <%# 投稿がないときの表示 %>
  </div>

app/views/posts/new.html.erb
<%= render "shared/header" %>

<div class="posts-post-contents">
  <div class="posts-post-main">
    <h2 class="posts-post-title">動画を投稿するかオススメのYouTube動画を紹介しよう！</h2>
    <%= form_with model: @post, url: posts_path, local: true do |f| %>
      <%= render 'shared/error_messages', model: f.object %>
      <div class="video-upload">
        <div class="weight-bold-text">
          動画ファイルを選択
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :video, id:"posts-video" %>
        </div>
      </div>
      <div class="new-posts">
        <h2 class="posts-post-text">Youtubeの動画を共有する場合は、こちらにURLを入力してください</h2>
        <%= f.text_area :youtube_url, class:"youtube-form", id:"post-youtube_url", placeholder:"YouTubeURL" %>
        <div class="weight-bold-text">
          詳細
        </div>
        <%= f.text_area :caption, class:"posts-text", id:"post-caption", placeholder:"タイトル", maxlength:"40" %>
        <%= f.text_area :describe, class:"posts-text", id:"post-describe", placeholder:"説明" ,rows:"7" ,maxlength:"1000" %>
        <%= f.text_area :place, class:"posts-text", id:"post-place", placeholder:"場所" %>
        <div class="weight-bold-text2">
          URL
        </div>
        <%= f.text_area :share_url, class:"posts-url", id:"post-share_url", placeholder:"オススメのお店や観光スポットをURLやテキストを付けて共有しよう!" %>
      </div>
      <div class="post-btn-contents">
        <%= f.submit "投稿する" ,class:"post-btn" %>
      </div>
    <% end %>
  </div>
</div>

<%= render "shared/second-footer" %>

app/views/posts/show.html.erb
<%= render "shared/header" %>

<div class="post-show-contents">
  <div class="post-show-content">
    <div class="post-video-content">
      <%# 投稿が動画かyoutubeの共有かを判断 %>
      <%if @post.video.present? %>
        <video class="post-video-show" src="<%= rails_blob_path(@post.video) %>"type="video/mp4" controls></video>
      <% elsif @post.youtube_url.present? %>
        <iframe class="post-video-show" height="500" src="https://www.youtube.com/embed/<%= @post.youtube_url%>" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
      <% end %>
      <%# /投稿が動画かyoutubuの共有かを判断 %>
    </div>
    <div class="post-show-caption">
      <div class="post-caption"><%= @post.caption %></div>
      
      <%# 編集,削除機能 %>
      <% if @post.user_id == current_user.id %>
        <button type="button" class= "btn btn-secondary float-right btn-sm" data-toggle="modal" data-target="#exampleModal1">
          投稿の削除
        </button>
        <div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">投稿の削除</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                投稿を完全に削除しますか？
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
                <%= link_to "投稿の削除", post_path(@post.id), method: :delete, class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        </div>
        <div class="post-show-btn float-right">
          <%= button_to "投稿の編集", edit_post_path(@post.id), method: :get, class: "btn btn-secondary btn-sm" %>
        </div>
      <% end %>
      <%# /編集、削除機能 %>

      <div class="post-time">
        <%= time_ago_in_words(@post.created_at)+"前に投稿" %>
        <% if @post.youtube_url.present? %>
          <span class="post-youtube">Youtube動画の共有</span>
        <% end %>
      </div>
    </div>

    <div class="post-show-user">
      <%= link_to user_path(@post.user.id), class: "post-show-user-link" do %>
        <% if @post.user.image.present? %>
          <%= image_tag @post.user.image, class: "post-show-user-icon" %>
        <% else %>
          <%= image_tag "profile_icon.png", class: "post-show-user-icon" %>
        <% end %>
        <%= @post.user.user_name %>
      <% end %>
      <div class="float-right">
        <div id="favorites_buttons_<%= @post.id %>">
          <%= render partial: 'favorites/favorite', locals: { post: @post} %>
        </div>
      </div>
    </div>
    <% if @post.describe.present? %>
      <div class="post-show-describe">
        <p><%=safe_join(@post.describe.split("\n"),tag(:br)) %></p>
      </div>
    <% end %>
    <% if @post.share_url.present? %>
      <div class="post-show-url">
        <h2 class="post-show-link-title">オススメ</h2>
        <%= Rinku.auto_link(@post.share_url, :all, 'target="_blank"').html_safe %>
      </div>
    <% end %>
    <%# 場所が入力されていたらmapを表示 %>
    <% if @post.place.present?%>
      <div class="post-show-place">
        <%= @post.place %>
      </div>
      <%= render 'shared/map', collection: @post %>
    <% end %>
    <%# /場所が入力されていたらmapを表示 %>

    <%# コメントの表示 %>
    <div class="post-show-comments">
      <div class="comments-text"><%= @comments.count %>件のコメント</div>
      <% if user_signed_in? %>
        <div class="comment-create">
          <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
        </div>
      <% end %>
      <div class="comments-list">
        <ul>
          <li id="comments_area">
            <%= render partial: 'comments/index', locals: { comments: @comments } %>
          </li>
        </ul>
      </div>
    </div>
    <%# /コメントの表示 %>
  </div>
</div>

<%= render "shared/footer" %>

app/views/relationships/create.js.erb
$("#follow_count").html("<%= j(render("users/follow_count")) %>");
$("#follow_btn").html("<%= j(render("users/follow_btn")) %>");

app/views/shared/_header.html.erb
<header class='top-page-header'>
  <div class='search-bar-contents'>
    <div class="header-img">
      <%= link_to image_tag("logo (2).png", class: "roots-icon2"), "/" %>
    </div>
    <%= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form| %>
      <%= form.text_field :keyword, placeholder: "検索", class: "input-box" %>
    <% end %>

    <div class='nav'>
      <div class='lists-right'>
        <% if user_signed_in? %>
          <div class="icons">
            <%= link_to image_tag("家のアイコン素材.png", class: "header-home-icon"), "/", class: "home-link" %>
            <%= link_to image_tag("post-new.png", class: "post-new-icon"), new_post_path, class: "post-link" %>
            <%= link_to image_tag("星アイコン.png", class: "header-star-icon"), favorites_posts_path(current_user.id), class: "star-link"%>
            <div class="dropdown">
              <div class="header-user-icon" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%# プロフィール画像の登録状態で表示を変更 %>
                <% if current_user.image.present? %>
                  <%= image_tag current_user.image, class: "user-icon" %>
                <% else %>
                  <%= image_tag "profile_icon.png", class: "user-icon" %>
                <% end %>
                <%# /プロフィール画像の登録状態で表示を変更 %>
              </div>
              
              <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <%= link_to "プロフィール", user_path(current_user.id), class: "dropdown-item" %>
                <%= link_to "プロフィール編集", edit_user_path(current_user.id), class: "dropdown-item"%>
                <%= link_to "お気に入り一覧", favorites_posts_path(current_user.id), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </div>
          <div>
        <% else %> 
          <%# 未ログイン時の表示 %>
          <div class="login-signup">
            <%= link_to "ログイン", new_user_session_path, class: "header-login" %>
            <%= link_to "新規登録", new_user_registration_path, class: "header-signup" %>
          </div>
          <%# / 未ログイン時の表示 %>
        <% end %>
      </div>
    </div>
  </div>
</header>

app/views/users/_follow_btn.html.erb
<% if user_signed_in? && @user != current_user %>
  <div id="follow_btn" class="follow-btns">
    <% if current_user.following?(@user) %>
      <div class="follow-form2">
        <button type="button" class="follow-btn2" data-toggle="modal" data-target="#exampleModalCenter">
          フォロー中
        </button>
      </div>
      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-body mx-auto">
              <% if @user.image.present? %>
                <%= image_tag @user.image, class: "follow-delete-icon" %>
              <% else %>
                <%= image_tag "profile_icon.png", class: "follow-delete-icon" %>
              <% end %>
            </div>
            <div class="follow-text mx-auto"><%= @user.user_name %>のフォローをやめますか？</div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
              <%= link_to "フォローをはずす", relationship_path(@user), method: :delete, remote: true, class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <%= form_with(url: relationships_path, method: :post, remote: true, class: "follow-form") do |f| %>
        <%= hidden_field_tag :following_id, @user.id %>
        <%= f.submit "フォローする", class: "follow-btn" %>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/_follow_count.html.erb
<div id="follow_count">
  <%= link_to followers_user_path(@user.id), class: "follow-link" do %>
    フォロワー<%= @user.followers.count %>人
  <% end %>
  <%= link_to following_user_path(@user.id), class: "follow-link" do %>
    フォロー中<%= @user.following.count %>人
  <% end %>
</div>